branch name

diff --git a/.github/workflows/check-pr.yml b/.github/workflows/check-pr.yml
--- a/.github/workflows/check-pr.yml
+++ b/.github/workflows/check-pr.yml
@@ -16,3 +16,15 @@ jobs:
         uses: pelotech/github-action-file-size-checker@v0.1.2
         with:
           max_file_size_kib: '100'
+
+
+  branch-name-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: branch-name-check
+        run: |
+          echo "Branch name is: ${{ github.head_ref }}"
+           if [[ ! "${{ github.head_ref }}" =~ ^(feature|fix|docs)/ ]]; then
+          echo "Invalid branch name. Use feature/*, fix/*, or docs/*"
+          exit 1
+
